### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by adyekjaer** [trustpilot/dockerlogger#9]
@sqdk 

On ECS, the docker inspect command reveals the following piece of information:

            ....
            "Labels": {
                "com.amazonaws.ecs.cluster": "cluster",
                "com.amazonaws.ecs.container-name": "servicename",
                "com.amazonaws.ecs.task-arn": "arn",
                "com.amazonaws.ecs.task-definition-family": "task definition",
                "com.amazonaws.ecs.task-definition-version": "00"
            }
           ....

Would it be possible to include the "com.amazonaws.ecs.container-name" in an ContainerName field for easy searching ?

Possibly using the Name variable when above does not exist to make sure dockerlogger works in non-ECS environments.

Thx!

**Comment by sqdk** [comment]
https://trello.com/c/wTrCHvbx
